### ISSUE TITLE
But Can It Be Done In Powerpoint

### ISSUE THREAD

**Issue by Jaiko657** [Pickfordmatt/SharpLocker#19]
Some people need a way to get round stupid restrictions that block exe files from running on user accounts. But these accounts are sometimes the accounts that you want to RECOVER ;D.

This is a project that has taken me a couple of hours to figure out but I thought u guys might like it.
 It combines the Idea of SharpLocker and the Fun that can be had in POWERPOINT.

Unfortunately GitHub does not like macro enabled PowerPoint so you're going to have to download it as a ZIP file as PowerPoint files are just ZIP files and then Rename to SharpLocker.pptm.
You should not download any PPTM file someone sends so if you want to download in a VM to test then by all means do. Any developments will be greatly appreciated

To Turn it into a proper "EXE" file then save as a .ppsm and it will launch the same as SharpLocker.

The VBA script Outputs a text file called creds.txt to the folder the PowerPoint is opened.

[Sharplocker.zip](https://github.com/Pickfordmatt/SharpLocker/files/4191201/Sharplocker.zip)

Having Issues getting the creds output to work after changing back from ZIP file so just right click the text box on the powerpoint and view code to understand it promise it is worth it xD

**Comment by Pickfordmatt** [comment]
Hi,

Glad you've had fun working on it, I can't recommend anyone clicks that link (do at your own risk).

SharpLocker is not intended to be run as an EXE.

Cheers,
Matt
