### ISSUE TITLE
Can't see the code in Visual Studio 2019

### ISSUE THREAD

**Issue by tacobitz** [Pickfordmatt/SharpLocker#24]
I Can't see the code in Visual Studio 2019. am I the only one who is experiencing it. Any help would be greatly appreciated 
![image](https://user-images.githubusercontent.com/67057784/84985628-c5589c80-b145-11ea-9ba0-5105e721e943.png)

**Comment by Something-Ramdom** [comment]
Use Visual Studio Code

**Comment by Something-Ramdom** [comment]
Because I have done the same problem

**Comment by Pickfordmatt** [comment]
Apologies for an incredibly late reply, as above try Visual Studio. Thanks
