### ISSUE TITLE
Cannot debug or run compiled exe

### ISSUE THREAD

**Issue by bluegizmo83** [Pickfordmatt/SharpLocker#27]
Can not debug or run the compiled exe, it keeps flagging it as a virus.
![Error](https://user-images.githubusercontent.com/1000998/98642415-b045fb00-22ea-11eb-88b5-d327a01ca196.jpg)

**Comment by Pickfordmatt** [comment]
Disable AV or find a work around such as moving the code / renaming functions and variables etc.
