### ISSUE TITLE
Writing Pw into .txt

### ISSUE THREAD

**Issue by cs-spacecat** [Pickfordmatt/SharpLocker#29]
Hi there, I have no clue from c or c# I only know Python a bit. Anyway, I wanted to ask if you could help me. I want to write the Password into a .txt file so that no network connection is needed. Can someone help me?
(for the fork from feb 9th)

**Comment by Pickfordmatt** [comment]
A network connection isn't needed, the output is passed to STD OUT, I'm not going to change this functionality to enable writing to a file its bad practice. Sorry!
